name: Flutter Analyze
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: 
       - master 
       - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'dev'
    - run: flutter pub get
    - run: flutter analyze
